# Generated by Django 5.2 on 2026-04-14 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_archive', models.FileField(upload_to='work/source')),
                ('extraction_root', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_directories', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_batches_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.TextField(db_index=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('is_directory', models.BooleanField(default=False)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('file_type', models.CharField(choices=[('DIRECTORY', 'Directory'), ('PDF', 'Pdf'), ('DOCX', 'Docx'), ('EXCEL', 'Excel'), ('ZIP', 'Zip'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('count_type', models.CharField(choices=[('NONE', 'None'), ('PAGE', 'Page'), ('ROW', 'Row'), ('LINE', 'Line')], default='NONE', max_length=10)),
                ('count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core_work.workbatch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_work.workfile')),
            ],
            options={
                'ordering': ['relative_path'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'relative_path'), name='unique_work_file_path_per_batch')],
            },
        ),
    ]
