# Generated by Django 5.2 on 2026-04-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_client', '0001_initial'),
        ('core_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatch',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_batches', to='core_client.client'),
        ),
    ]
