# Generated by Django 5.2 on 2026-04-15 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0002_workbatch_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('unit_number', models.PositiveIntegerField(default=1)),
                ('range_start', models.PositiveBigIntegerField(blank=True, null=True)),
                ('range_end', models.PositiveBigIntegerField(blank=True, null=True)),
                ('count_type', models.CharField(choices=[('NONE', 'None'), ('PAGE', 'Page'), ('ROW', 'Row'), ('LINE', 'Line')], default='NONE', max_length=10)),
                ('workload_count', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED_TO_PRODUCTION', 'Assigned To Production'), ('IN_VALIDATION', 'In Validation'), ('REDO', 'Redo'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=32)),
                ('production_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('production_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('redo_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_units', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core_work.workbatch')),
                ('current_production_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_work_units', to=settings.AUTH_USER_MODEL)),
                ('current_validation_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_work_units', to=settings.AUTH_USER_MODEL)),
                ('work_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core_work.workfile')),
            ],
            options={
                'ordering': ['work_file__relative_path', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkUnitAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('ISSUE', 'Issue'), ('OVERDUE', 'Overdue')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_work_alerts', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core_work.workunit')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('PRODUCTION', 'Production'), ('VALIDATION', 'Validation')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_unit_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_unit_assignments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core_work.workunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workunit',
            constraint=models.UniqueConstraint(fields=('batch', 'work_file', 'unit_number'), name='unique_work_unit_per_file_split'),
        ),
    ]
