# Generated by Django 5.2 on 2026-04-15 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0003_workunit_workunitalert_workunitassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='production_output',
            field=models.FileField(blank=True, null=True, upload_to='work/production_output'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='production_output_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workunit',
            name='validator_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkBatchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('PRODUCTION', 'Production'), ('VALIDATION', 'Validation')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core_work.workbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_batch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'user', 'role'), name='unique_work_batch_member_role')],
            },
        ),
    ]
