# Generated by Django 5.2 on 2026-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0004_workunit_production_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatch',
            name='auto_batch_size_per_production_user',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='workbatch',
            name='auto_refill_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workbatch',
            name='overdue_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
