# Generated by Django 5.2 on 2026-04-15 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0005_workbatch_auto_batch_size_per_production_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatch',
            name='delivery_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('CLIENT_REVIEW_PENDING', 'Client Review Pending'), ('REWORK_REQUESTED', 'Rework Requested'), ('SIGNED_OFF', 'Signed Off')], db_index=True, default='IN_PROGRESS', max_length=32),
        ),
        migrations.AddField(
            model_name='workbatch',
            name='initiated_by_sme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_work_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('review_file', models.FileField(upload_to='work/client_review')),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_to_sme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_reviews', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='core_work.workbatch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDeliveryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('COMPLETED_ONLY', 'Completed Only'), ('INCLUDE_INCOMPLETE', 'Include Incomplete')], db_index=True, max_length=24)),
                ('archive', models.FileField(upload_to='work/delivery')),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_packages', to='core_work.workbatch')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_delivery_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
