# Generated by Django 5.2 on 2026-04-16 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_client', '0001_initial'),
        ('core_work', '0006_workbatch_delivery_status_workbatch_initiated_by_sme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveIntegerField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('trigger', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent')], db_index=True, default='GENERATED', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_invoices', to='core_client.client')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkFileBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_billings', to='core_work.workbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_file_billings', to='core_client.client')),
                ('work_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core_work.workfile')),
            ],
            options={
                'ordering': ['-completed_at', '-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkClientInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='core_work.workbatch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_work.workclientinvoice')),
                ('work_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='core_work.workfile')),
                ('work_file_billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='core_work.workfilebilling')),
            ],
            options={
                'ordering': ['batch__name', 'work_file__relative_path', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workclientinvoice',
            constraint=models.UniqueConstraint(fields=('client', 'year', 'month'), name='unique_client_invoice_per_month'),
        ),
    ]
