# Generated by Django 6.0.2 on 2026-04-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0006_workbatch_delivery_status_workbatch_initiated_by_sme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], db_index=True, default='PROCESSING', max_length=20),
        ),
    ]
