# Generated by Django 6.0.2 on 2026-04-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0008_backfill_completed_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='redo_report_file',
            field=models.FileField(blank=True, null=True, upload_to='work/redo_reports'),
        ),
    ]
