# Generated by Django 6.0.2 on 2026-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_work', '0009_add_redo_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('INACTIVE', 'Inactive')], db_index=True, default='PROCESSING', max_length=20),
        ),
    ]
