# Generated by Django 6.0.2 on 2026-04-25 05:31

import core.utils.unique_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.unique_file_path.UniqueFilePath('profile/images')),
        ),
    ]
